project_id = "cicwzhpsiewdpugmceqm"

[functions.register-installation]
verify_jwt = false

[functions.check-block-status]
verify_jwt = false

[functions.whatsapp-welcome]
verify_jwt = false

[functions.whatsapp-proxy]
verify_jwt = false

[functions.register-zapmeow]
verify_jwt = false

[functions.manage-installations]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false
