import { Router } from "express";

import userRoutes from "./userRoutes";
import authRoutes from "./authRoutes";
import settingRoutes from "./settingRoutes";
import contactRoutes from "./contactRoutes";
import ticketRoutes from "./ticketRoutes";
import whatsappRoutes from "./whatsappRoutes";
import messageRoutes from "./messageRoutes";
import whatsappSessionRoutes from "./whatsappSessionRoutes";
import queueRoutes from "./queueRoutes";
import companyRoutes from "./companyRoutes";
import planRoutes from "./planRoutes";
import ticketNoteRoutes from "./ticketNoteRoutes";
import quickMessageRoutes from "./quickMessageRoutes";
import helpRoutes from "./helpRoutes";
import dashboardRoutes from "./dashboardRoutes";
import scheduleRoutes from "./scheduleRoutes";
import tagRoutes from "./tagRoutes";
import contactListRoutes from "./contactListRoutes";
import contactListItemRoutes from "./contactListItemRoutes";
import campaignRoutes from "./campaignRoutes";
import campaignSettingRoutes from "./campaignSettingRoutes";
import announcementRoutes from "./announcementRoutes";
import chatRoutes from "./chatRoutes";
import queueIntegrationRoutes from "./queueIntegrationRoutes";
import chatBotRoutes from "./chatBotRoutes";
import webHookRoutes from "./webHookRoutes";
import subScriptionRoutes from "./subScriptionRoutes";
import invoiceRoutes from "./invoicesRoutes";
import apiRoutes from "./apiRoutes";
import versionRouter from "./versionRoutes";
import filesRoutes from "./filesRoutes";
import queueOptionRoutes from "./queueOptionRoutes";
import ticketTagRoutes from "./ticketTagRoutes";
import apiCompanyRoutes from "./api/apiCompanyRoutes";
import apiContactRoutes from "./api/apiContactRoutes";
import apiMessageRoutes from "./api/apiMessageRoutes";
import companySettingsRoutes from "./companySettingsRoutes";
import ticketFinalizationReasonRoutes from "./ticketFinalizationReasonRoutes";
import presetWebhookRoutes from "./presetWebhookRoutes";
import birthdayRoutes from "./birthdayRoutes";
import promptRoutes from "./promptRouter";
import statisticsRoutes from "./statisticsRoutes";
import scheduleMessageRoutes from "./ScheduledMessagesRoutes";
import flowDefaultRoutes from "./flowDefaultRoutes";
import webHook from "./webHookRoutes";
import flowBuilder from "./flowBuilderRoutes";
import flowCampaignRoutes from "./flowCampaignRoutes";
import callRoutes from "./callRoutes";
import companyKanbanRoutes from "./companyKanbanRoutes";
import floupApp from "../plugins/floup";
import installationLogRoutes from "./installationLogRoutes";
import backupRoutes from "./backupRoutes";
import pushNotificationRoutes from "./pushNotificationRoutes";
import n8nCallbackRoutes from "./n8nCallbackRoutes";
import interactiveTemplateRoutes from "./interactiveTemplateRoutes";
import interactiveRoutes from "./interactiveRoutes";
import warmerSettingsRoutes from "./warmerSettingsRoutes";
import metaTemplateRoutes from "./metaTemplateRoutes";
import warmerDraftRoutes from "./warmerDraftRoutes";
import metaTemplateVersionRoutes from "./metaTemplateVersionRoutes";
import apiKeyRoutes from "./apiKeyRoutes";
import apiV2Routes from "./api/apiV2Routes";
import apiV2Docs from "./api/apiV2Docs";

import ChatController from "../controllers/ChatController";

const routes = Router();

routes.use(userRoutes);
routes.use("/auth", authRoutes);
routes.use("/api/messages", apiRoutes);
routes.use(settingRoutes);
routes.use(contactRoutes);
routes.use(ticketRoutes);
routes.use(whatsappRoutes);
routes.use(messageRoutes);
routes.use(messageRoutes);
routes.use(whatsappSessionRoutes);
routes.use(queueRoutes);
routes.use(companyRoutes);
routes.use(planRoutes);
routes.use(ticketNoteRoutes);
routes.use(quickMessageRoutes);
routes.use(helpRoutes);
routes.use(dashboardRoutes);
routes.use(birthdayRoutes);
routes.use(scheduleRoutes);
routes.use(tagRoutes);
routes.use(contactListRoutes);
routes.use(contactListItemRoutes);
routes.use(campaignRoutes);
routes.use(campaignSettingRoutes);
routes.use(announcementRoutes);
routes.use(chatRoutes);
routes.use(chatBotRoutes);
routes.use("/webhook", webHookRoutes);
routes.use(subScriptionRoutes);
routes.use(invoiceRoutes);
routes.use(versionRouter);
routes.use(filesRoutes);
routes.use(queueOptionRoutes);
routes.use(queueIntegrationRoutes);
routes.use(ticketTagRoutes);
routes.use("/api", apiCompanyRoutes);
routes.use("/api", apiContactRoutes);
routes.use("/api", apiMessageRoutes);
routes.use(presetWebhookRoutes);
routes.use(promptRoutes);
routes.use(statisticsRoutes);
routes.use(companySettingsRoutes);
routes.use(ticketFinalizationReasonRoutes);
routes.use(scheduleMessageRoutes);

routes.use(flowDefaultRoutes);
routes.use(webHook);
routes.use(flowBuilder);
routes.use(flowCampaignRoutes);
routes.use("/call", callRoutes);
routes.use(companyKanbanRoutes);

// Plugins
routes.use(floupApp);

// Monitor de instalações (anti-pirataria)
routes.use(installationLogRoutes);
routes.use(backupRoutes);
routes.use(pushNotificationRoutes);
routes.use(n8nCallbackRoutes);
routes.use(interactiveTemplateRoutes);
routes.use(interactiveRoutes);
routes.use(warmerSettingsRoutes);
routes.use(metaTemplateRoutes);
routes.use(warmerDraftRoutes);
routes.use(metaTemplateVersionRoutes);

// API pública v2 (auth via X-API-Key) + docs Swagger
routes.use(apiKeyRoutes);
routes.use("/api/v2", apiV2Docs);
routes.use("/api/v2", apiV2Routes);

routes.post("/chats/backfill", ChatController.backfillChats);

export default routes;
